//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 03:25:36 PM EDT 
//


package org.immregistries.dqa.hl7util.parser.profile.intf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for segment complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="segment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Field" type="{}field" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="LongName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Max" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Min" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Usage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "segment", propOrder = {
    "field"
})
public class Segment implements HL7Segment {

  @XmlElement(name = "Field")
  protected List<Field> field;
  @XmlAttribute(name = "LongName")
  protected String longName;
  @XmlAttribute(name = "Max")
  protected String max;
  @XmlAttribute(name = "Min")
  protected Byte min;
  @XmlAttribute(name = "Name")
  protected String name;
  @XmlAttribute(name = "Usage")
  protected String usage;

  public List<Field> getField() {
    if (field == null) {
      field = new ArrayList<Field>();
    }
    return this.field;
  }

  public String getLongName() {
    return longName;
  }

  public void setLongName(String value) {
    this.longName = value;
  }

  /**
   * Gets the value of the max property.
   *
   * @return possible object is {@link String }
   */
  public String getMax() {
    return max;
  }

  /**
   * Sets the value of the max property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMax(String value) {
    this.max = value;
  }

  /**
   * Gets the value of the min property.
   *
   * @return possible object is {@link Byte }
   */
  public Byte getMin() {
    return min;
  }

  /**
   * Sets the value of the min property.
   *
   * @param value allowed object is {@link Byte }
   */
  public void setMin(Byte value) {
    this.min = value;
  }

  public String getName() {
    return name;
  }

  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the usage property.
   *
   * @return possible object is {@link String }
   */
  public String getUsage() {
    return usage;
  }

  /**
   * Sets the value of the usage property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUsage(String value) {
    this.usage = value;
  }

}
