//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 03:25:36 PM EDT 
//


package org.immregistries.dqa.hl7util.parser.profile.intf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.immregistries.dqa.hl7util.parser.profile.generated.ConformanceStatement;
import org.immregistries.dqa.hl7util.parser.profile.generated.Predicate;


/**
 * <p>Java class for subComponent complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="subComponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Predicate" type="{}predicate" minOccurs="0"/>
 *         &lt;element name="ConformanceStatement" type="{}conformanceStatement"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Datatype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MaxLength" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="MinLength" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Table" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="Usage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PredicateFalseUsage" type="{http://www.w3.org/2001/XMLSchema}string"
 * />
 *       &lt;attribute name="PredicateTrueUsage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subComponent", propOrder = {
    "predicate",
    "conformanceStatement"
})
public class SubComponent implements HL7SubComponent {

  @XmlElement(name = "Predicate")
  protected Predicate predicate;
  @XmlElement(name = "ConformanceStatement", required = true)
  protected ConformanceStatement conformanceStatement;
  @XmlAttribute(name = "Datatype")
  protected String datatype;
  @XmlAttribute(name = "MaxLength")
  protected Short maxLength;
  @XmlAttribute(name = "MinLength")
  protected Byte minLength;
  @XmlAttribute(name = "Name")
  protected String name;
  @XmlAttribute(name = "Table")
  protected Short table;
  @XmlAttribute(name = "Usage")
  protected String usage;
  @XmlAttribute(name = "PredicateFalseUsage")
  protected String predicateFalseUsage;
  @XmlAttribute(name = "PredicateTrueUsage")
  protected String predicateTrueUsage;

  /**
   * Gets the value of the predicate property.
   *
   * @return possible object is {@link Predicate }
   */
  public Predicate getPredicate() {
    return predicate;
  }

  /**
   * Sets the value of the predicate property.
   *
   * @param value allowed object is {@link Predicate }
   */
  public void setPredicate(Predicate value) {
    this.predicate = value;
  }

  /**
   * Gets the value of the conformanceStatement property.
   *
   * @return possible object is {@link ConformanceStatement }
   */
  public ConformanceStatement getConformanceStatement() {
    return conformanceStatement;
  }

  /**
   * Sets the value of the conformanceStatement property.
   *
   * @param value allowed object is {@link ConformanceStatement }
   */
  public void setConformanceStatement(ConformanceStatement value) {
    this.conformanceStatement = value;
  }

  /* (non-Javadoc)
   * @see org.immregistries.dqa.hl7util.parser.profile.generated.HL7SubComponent#getDatatype()
   */
  @Override
  public String getDatatype() {
    return datatype;
  }

  /**
   * Sets the value of the datatype property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDatatype(String value) {
    this.datatype = value;
  }

  /**
   * Gets the value of the maxLength property.
   *
   * @return possible object is {@link Short }
   */
  public Short getMaxLength() {
    return maxLength;
  }

  /**
   * Sets the value of the maxLength property.
   *
   * @param value allowed object is {@link Short }
   */
  public void setMaxLength(Short value) {
    this.maxLength = value;
  }

  /**
   * Gets the value of the minLength property.
   *
   * @return possible object is {@link Byte }
   */
  public Byte getMinLength() {
    return minLength;
  }

  /**
   * Sets the value of the minLength property.
   *
   * @param value allowed object is {@link Byte }
   */
  public void setMinLength(Byte value) {
    this.minLength = value;
  }

  /* (non-Javadoc)
   * @see org.immregistries.dqa.hl7util.parser.profile.generated.HL7SubComponent#getName()
   */
  @Override
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the table property.
   *
   * @return possible object is {@link Short }
   */
  public Short getTable() {
    return table;
  }

  /**
   * Sets the value of the table property.
   *
   * @param value allowed object is {@link Short }
   */
  public void setTable(Short value) {
    this.table = value;
  }

  /**
   * Gets the value of the usage property.
   *
   * @return possible object is {@link String }
   */
  public String getUsage() {
    return usage;
  }

  /**
   * Sets the value of the usage property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUsage(String value) {
    this.usage = value;
  }

  /**
   * Gets the value of the predicateFalseUsage property.
   *
   * @return possible object is {@link String }
   */
  public String getPredicateFalseUsage() {
    return predicateFalseUsage;
  }

  /**
   * Sets the value of the predicateFalseUsage property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPredicateFalseUsage(String value) {
    this.predicateFalseUsage = value;
  }

  /**
   * Gets the value of the predicateTrueUsage property.
   *
   * @return possible object is {@link String }
   */
  public String getPredicateTrueUsage() {
    return predicateTrueUsage;
  }

  /**
   * Sets the value of the predicateTrueUsage property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPredicateTrueUsage(String value) {
    this.predicateTrueUsage = value;
  }

}
