//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 03:25:36 PM EDT 
//


package org.immregistries.mqe.hl7util.parser.profile.intf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.immregistries.mqe.hl7util.parser.profile.generated.ConformanceStatement;
import org.immregistries.mqe.hl7util.parser.profile.generated.Predicate;


/**
 * <p>Java class for field complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="field">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ConformanceStatement" type="{}conformanceStatement"/>
 *         &lt;element name="Predicate" type="{}predicate"/>
 *         &lt;element name="Component" type="{}component" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="Datatype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Max" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MaxLength" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="Min" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MinLength" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Usage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Table" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PredicateFalseUsage" type="{http://www.w3.org/2001/XMLSchema}string"
 * />
 *       &lt;attribute name="PredicateTrueUsage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "field", propOrder = {
    "conformanceStatement",
    "predicate",
    "component"
})
public class Field implements HL7Field {

  @XmlElement(name = "ConformanceStatement")
  protected ConformanceStatement conformanceStatement;
  @XmlElement(name = "Predicate")
  protected Predicate predicate;
  @XmlElement(name = "Component")
  protected List<Component> component;
  @XmlAttribute(name = "Datatype")
  protected String datatype;
  @XmlAttribute(name = "Max")
  protected String max;
  @XmlAttribute(name = "MaxLength")
  protected String maxLength;
  @XmlAttribute(name = "Min")
  protected Byte min;
  @XmlAttribute(name = "MinLength")
  protected Byte minLength;
  @XmlAttribute(name = "Name")
  protected String name;
  @XmlAttribute(name = "Usage")
  protected String usage;
  @XmlAttribute(name = "Table")
  protected String table;
  @XmlAttribute(name = "PredicateFalseUsage")
  protected String predicateFalseUsage;
  @XmlAttribute(name = "PredicateTrueUsage")
  protected String predicateTrueUsage;

  /**
   * Gets the value of the conformanceStatement property.
   *
   * @return possible object is {@link ConformanceStatement }
   */
  public ConformanceStatement getConformanceStatement() {
    return conformanceStatement;
  }

  /**
   * Sets the value of the conformanceStatement property.
   *
   * @param value allowed object is {@link ConformanceStatement }
   */
  public void setConformanceStatement(ConformanceStatement value) {
    this.conformanceStatement = value;
  }

  /**
   * Gets the value of the predicate property.
   *
   * @return possible object is {@link Predicate }
   */
  public Predicate getPredicate() {
    return predicate;
  }

  /**
   * Sets the value of the predicate property.
   *
   * @param value allowed object is {@link Predicate }
   */
  public void setPredicate(Predicate value) {
    this.predicate = value;
  }

  public List<Component> getComponent() {
    if (component == null) {
      component = new ArrayList<Component>();
    }
    return this.component;
  }

  public String getDatatype() {
    return datatype;
  }

  /**
   * Sets the value of the datatype property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDatatype(String value) {
    this.datatype = value;
  }

  /**
   * Gets the value of the max property.
   *
   * @return possible object is {@link String }
   */
  public String getMax() {
    return max;
  }

  /**
   * Sets the value of the max property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMax(String value) {
    this.max = value;
  }

  /**
   * Gets the value of the maxLength property.
   *
   * @return possible object is {@link Short }
   */
  public String getMaxLength() {
    return maxLength;
  }

  /**
   * Sets the value of the maxLength property.
   *
   * @param value allowed object is {@link Short }
   */
  public void setMaxLength(String value) {
    this.maxLength = value;
  }

  /**
   * Gets the value of the min property.
   *
   * @return possible object is {@link Byte }
   */
  public Byte getMin() {
    return min;
  }

  /**
   * Sets the value of the min property.
   *
   * @param value allowed object is {@link Byte }
   */
  public void setMin(Byte value) {
    this.min = value;
  }

  /**
   * Gets the value of the minLength property.
   *
   * @return possible object is {@link Byte }
   */
  public Byte getMinLength() {
    return minLength;
  }

  /**
   * Sets the value of the minLength property.
   *
   * @param value allowed object is {@link Byte }
   */
  public void setMinLength(Byte value) {
    this.minLength = value;
  }

  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the usage property.
   *
   * @return possible object is {@link String }
   */
  public String getUsage() {
    return usage;
  }

  /**
   * Sets the value of the usage property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUsage(String value) {
    this.usage = value;
  }

  /**
   * Gets the value of the table property.
   *
   * @return possible object is {@link String }
   */
  public String getTable() {
    return table;
  }

  /**
   * Sets the value of the table property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTable(String value) {
    this.table = value;
  }

  /**
   * Gets the value of the predicateFalseUsage property.
   *
   * @return possible object is {@link String }
   */
  public String getPredicateFalseUsage() {
    return predicateFalseUsage;
  }

  /**
   * Sets the value of the predicateFalseUsage property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPredicateFalseUsage(String value) {
    this.predicateFalseUsage = value;
  }

  /**
   * Gets the value of the predicateTrueUsage property.
   *
   * @return possible object is {@link String }
   */
  public String getPredicateTrueUsage() {
    return predicateTrueUsage;
  }

  /**
   * Sets the value of the predicateTrueUsage property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPredicateTrueUsage(String value) {
    this.predicateTrueUsage = value;
  }

}
